### PR TITLE
Manage dhcp workflow

### PR DESCRIPTION
**Pull request by christophermmeyer**
Add the manage_dhcp workflow to the Community folder. This contains a set of endpoints to handle various aspects to managing DHCP.

### CODE REVIEW

**Comment by nikhiljangi** [comment]
DS store file (Community/Service Requests/.DS_Store) appears to be accidentally added to the pull request. Please remove the same.

**Comment by sharma-anshul** [comment]
Hey @christophermmeyer this pull request should only contain the files related to the Manage DHCP workflow, but it seems to contain commits related to Manage Records and Service Requests as well. Those files would have to be removed before we can merge this in.

**Comment by christophermmeyer** [comment]
@sharma-anshul All set on the updates. I removed the files as requested and updated the dates. Should be good to go!

**Comment by christophermmeyer** [comment]
I'm killing this pull request and branch to get a clean version up and running.

**Pull request closed without merging**
